### ISSUE TITLE
Novo paywall Financial Times

### ISSUE THREAD

**Issue by danilofreire** [burlesco/userscript#13]
Olá pessoal!

Hoje aparentemente o Financial Times mudou o funcionamento do paywall. Até ontem o burlesco estava funcionando normalmente (Firefox+TamperMonkey+macOS), mas as matérias agora aparecem bloqueadas. Caso seja possível restaurar a funcionalidade no site, eu agradeço bastante. Fico também disposto a ajudar no que for necessário. Valeu! 😃

**Comment by rodorgas** [comment]
Obrigado, corrigido em #35.
