### ISSUE TITLE
O Globo

### ISSUE THREAD

**Issue by CaioWzy** [burlesco/userscript#23]
Relata-se problema com O Globo.

**Comment by rodorgas** [comment]
É verdade, fui tentar ler hoje rs

**Comment by CaioWzy** [comment]
Bom, atualizaram o Tiny.js mas bloqueando resolve, o problema é que impede
o carregamento do Acervo. Por algum motivo o script não está baixando via
xhr para eu testar os novos patches.

**Comment by kemelzaidan** [comment]
Isso já não foi corrigido? Ao acessar a página, parece tudo normal...

**Comment by rodorgas** [comment]
Também me parece estar funcionando normalmente
