### ISSUE TITLE
Userscript não funciona mais no Nexo

### ISSUE THREAD

**Issue by Kaoticz** [burlesco/userscript#29]
Parece que eles atualizaram o paywal. [Link de referência](https://www.nexojornal.com.br/expresso/2019/11/19/Qual-a-situação-legal-de-Julian-Assange-fundador-do-Wikileaks)

Versão 11.17, Tampermonkey, Chrome.

**Comment by rodorgas** [comment]
Nexo passou a usar hard paywall https://github.com/burlesco/burlesco/issues/320
